### ISSUE TITLE
Not Showing on My Discord on Fedora 31 using NVIM

### ISSUE THREAD

**Issue by benyaminl** [ObserverOfTime/discord.nvim#1]
Hello. I want to ask, is there anything I miss when installing, the status won't show on my discord using nvim and discord 0.0.9 using copr discord installer. 
This's my nvim detail
```
version   
NVIM v0.4.3                                                                                                                    
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fst
ack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1
 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=
1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -W
missing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_G
NU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/build/BUILD/neovim-0.4.3/build/config -I/builddir/build/BUIL
D/neovim-0.4.3/src -I/usr/include -I/usr/include/lua-5.1 -I/builddir/build/BUILD/neovim-0.4.3/build/src/nvim/auto -I/builddir/build/BUI
LD/neovim-0.4.3/build/include
Compiled by mockbuild

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
version   
NVIM v0.4.3                                                                                                                    
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fst
ack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1
 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=
1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -W
missing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_G
NU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/build/BUILD/neovim-0.4.3/build/config -I/builddir/build/BUIL
D/neovim-0.4.3/src -I/usr/include -I/usr/include/lua-5.1 -I/builddir/build/BUILD/neovim-0.4.3/build/src/nvim/auto -I/builddir/build/BUI
LD/neovim-0.4.3/build/include
Compiled by mockbuild

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
And this's my nvim health. Upon start up it can detect the discord local client available or not, if my discord offline then it says no local client found, but when it's on it throw and error no notification handler registered for "/home/ben/.local/share/nvim/plugged/discord.nvim/rplugin/python3/discord:autocmd:VimEnter:*" and It doesn't update the discord presence. Please can you kindly help me. Thank you

**Comment by benyaminl** [comment]
It's working, seems I need to change the branch to refactored. Thank you 
![image](https://user-images.githubusercontent.com/2817332/71548418-55602980-29e0-11ea-8c16-21cfdef03cb5.png)

**Comment by ObserverOfTime** [comment]
You didn't need to change the branch, `refactored` is the default branch of the fork.

This is an issue that seems to appear at random (see aurieh#22 and the linked issues).
I just pushed 9f5430b which includes the same potential fix as the aforementioned PR.
