### ISSUE TITLE
Plugin Working ! But when I open some file nvim seems to lag and I checked, its because of this plugin

### ISSUE THREAD

**Issue by ashwinkhode** [ObserverOfTime/discord.nvim#6]
Cursor blinks rapidly and nvim lagging
Seems something is loading continuously behind the scene
Plugin works successfully but now this problem occurs
OS : Win10
Any idea?

**Comment by ObserverOfTime** [comment]
Does [TTtie/discord.nvim](https://github.com/TTtie/discord.nvim) also lag?

**Comment by ashwinkhode** [comment]
It doesnt work like yours ! but yeah there's no lag in TTtie's plugin

**Comment by ObserverOfTime** [comment]
Try the [ft-cache](https://github.com/ObserverOfTime/discord.nvim/tree/ft-cache) and [close-pipe](https://github.com/ObserverOfTime/discord.nvim/tree/close-pipe) branches and see if either of them fixes the lag.

**Comment by ashwinkhode** [comment]
Nevermind ! coc-cord worked for me ! Thanks !
