### ISSUE TITLE
Error on BufEnter

### ISSUE THREAD

**Issue by Luc-Saccoccio** [ObserverOfTime/discord.nvim#7]
I got an error whe opening nvim :
```
Erreur détectée en traitant function remote#define#request :
ligne    2 :
Error invoking '/home/luc/.dotfiles/nvim/.config/nvim/plugged/discord.nvim/rplugin/python3/discord:auto
cmd:BufEnter:*' on channel 3 (python3-rplugin-host):
error caught in request handler '/home/luc/.dotfiles/nvim/.config/nvim/plugged/discord.nvim/rplugin/pyt
hon3/discord:autocmd:BufEnter:* []':
Traceback (most recent call last):
  File "/home/luc/.dotfiles/nvim/.config/nvim/plugged/discord.nvim/rplugin/python3/discord/__init__.py"
, line 55, in on_bufenter
    self.update_presence()
  File "/home/luc/.dotfiles/nvim/.config/nvim/plugged/discord.nvim/rplugin/python3/discord/__init__.py"
, line 67, in update_presence
    if self.project_url:
AttributeError: 'DiscordPlugin' object has no attribute 'project_url'
```
(The first line is saying `Error detected while treating fucntion remote#define#request`, I'm french, sorry ^^)
What is the problem ? Am I missing dependencies ?

**Comment by ObserverOfTime** [comment]
Try removing `~/.config/nvim/plugged/discord.nvim` and reinstalling it.

**Comment by Luc-Saccoccio** [comment]
Same error

**Comment by ObserverOfTime** [comment]
My bad, it's `~/.dotfiles/nvim/.config/nvim/plugged/discord.nvim`.
If the issue occurs after removing that, check whether this is in `__init__.py`:
https://github.com/ObserverOfTime/discord.nvim/blob/7c2737f2ce1082feed75f99f98006388e60b81fd/rplugin/python3/discord/__init__.py#L27

**Comment by Luc-Saccoccio** [comment]
Removing it in .config or in .dotfiles is the same (they are linked, I'm sorry, I forgot to mention that).
On the other hand, I don't have the line you mentionned. In fact, my file is way smaller (163 lines) than yours (238), and I don't really understand why.

**Comment by ObserverOfTime** [comment]
That's weird. Go to the plugin folder and run `git remote show origin`.

**Comment by Luc-Saccoccio** [comment]
Here is the output
```
* distante origin
  URL de rapatriement : https://github.com/ObserverOfTime/discord.nvim.git
  URL push : https://github.com/ObserverOfTime/discord.nvim.git
  Branche HEAD : refactored
  Branches distantes :
    master         suivi
    refactored     suivi
    rfc/close-pipe suivi
    wip/idle-timer suivi
  Branches locales configurées pour 'git pull' :
    master     fusionne avec la distante master
    refactored fusionne avec la distante refactored
  Références locales configurées pour 'git push' :
    master     pousse vers master     (à jour)
    refactored pousse vers refactored (à jour)
```
If you have any problem with french words, just tell me

**Comment by ObserverOfTime** [comment]
What about `git log HEAD^`?

**Comment by Luc-Saccoccio** [comment]
```
commit 3be119f5c89b03a241bf00522b504729f2543d5b (grafted, HEAD -> master, origin/master)
Author: ObserverOfTime <chronobserver@disroot.org>
Date:   Thu Jan 14 14:09:47 2021 +0200

    Add project URL to rich presence
```

**Comment by ObserverOfTime** [comment]
Run `git fetch --unshallow && git reset --hard origin/refactored` and it should be fixed.

**Comment by Luc-Saccoccio** [comment]
Well, it's almost fixed, now I just need to figure out why nothing is appearing on Discord. [The first error I mentionned](https://github.com/ObserverOfTime/discord.nvim/issues/7#issue-795136018) is fixed (I guess), nothing is showing on startup.

**Comment by ObserverOfTime** [comment]
> For your custom status to show up on Discord, "Display currently running game as a status message" must be enabled under Settings -> (App settings) Games.

**Comment by Luc-Saccoccio** [comment]
Sorry ^^
Thanks a lot for helping me !
